name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore

env:
  GIT_USER: barretlee
  GIT_EMAIL: barret.china@gmail.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-add ~/.ssh/github_deploy
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install
        working-directory: blog

      - name: Deploy hexo
        run: |
          npm run deploy
        working-directory: blog